import unittest
from main import counting_dna_nucleotides


class TestCountingDNANucleotides(unittest.TestCase):

    def test_case_01(self):
        test_input = 'AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC'
        expect = '20 12 17 21'
        actual = counting_dna_nucleotides(test_input)

        self.assertEqual(expect, actual)

    def test_case_02(self):
        test_input = 'CTATAATGATACCATGACTGACTGCACCCGAGCTCCCTTGGTTGCGAAAGCGTCCTCTCCGATCAATGGATTCTTGCCACCTAGACACAACCATCGAACGAGTAAATCACAGTCAACCCTTCGACTGTCGACGAACCGAGTCTCCGTCCGGCGCAAGTCTAATTGGATCCATAGTCCTGGGATTTGAGTTACGCTTTATCCGAGTCGGGTTTGGAGTGCAATGATTAGGATGTCAAATGCGGGATTCAGCAAACCCTAGATTGCGGACGTCGTTTCAATCCTATAACACGACTTACTAAGACCCCGCAATCGCGGAATTGCATAGCTCTCTGCAGTTCTTCACGACCCTACGTCACTCCCCGTCTACTAATGGCAATACAGCACTCATGACAGTGTTGAACAATATGCTGGAACCACGTTTGGTGACAAGATGCTAAACACAGGCCATTACGTACGTTTAATAAACTAATTAACTAAGGTATAAACAGAGAAGACGTAGTTCGTGTCTTGCTTGGCCGGGCTCTTTCATGTCCATGGTAACATACCAGAACCCTCAGCAAACTTTTATGTTCCGAGTCAAATTTCTACTGGAGGACACCAGTCGGGTTTTATAAGGGGCGCCTGGTTCCGACAGCACACATAACAGATCAGATATCTGGACCGGGCGCACCGGTGTCTCAAGGGCACGAATGGTTGTCAGAGGGCCCAAACTAGCTTGACCCTTGCCGAACTAAAGAACGTGCGTTTTTGATAGATACTAGGGAGACCGGTTGCGATGACGAGGGGACTATCGTCAACGTCGTGACTAGGGACCTCAGCGCTAAGCTTCGGCCTG'
        expect = '221 213 197 204'
        actual = counting_dna_nucleotides(test_input)

        self.assertEqual(expect, actual)

if __name__ == '__main__':
    unittest.main()
